# Builds the Expo Router web export (static PWA) and serves it with nginx.
# Expo SDK 57 requires Node >= 22.13.

FROM node:22-slim AS builder
WORKDIR /app

# EXPO_PUBLIC_* values are inlined into the JS bundle at build time by Metro — they must be
# passed as Docker BUILD ARGS (Easypanel: "Build Args" / "Build-time variables"), not as regular
# runtime environment variables, which would never reach this build step.
ARG EXPO_PUBLIC_APPWRITE_ENDPOINT
ARG EXPO_PUBLIC_APPWRITE_PROJECT_ID
ARG EXPO_PUBLIC_APPWRITE_DATABASE_ID
ARG EXPO_PUBLIC_APPWRITE_SETTINGS_COLLECTION_ID
ARG EXPO_PUBLIC_APPWRITE_RECORDINGS_COLLECTION_ID
ARG EXPO_PUBLIC_APPWRITE_SEGMENTS_COLLECTION_ID
ARG EXPO_PUBLIC_APPWRITE_BUCKET_ID
ENV EXPO_PUBLIC_APPWRITE_ENDPOINT=$EXPO_PUBLIC_APPWRITE_ENDPOINT \
    EXPO_PUBLIC_APPWRITE_PROJECT_ID=$EXPO_PUBLIC_APPWRITE_PROJECT_ID \
    EXPO_PUBLIC_APPWRITE_DATABASE_ID=$EXPO_PUBLIC_APPWRITE_DATABASE_ID \
    EXPO_PUBLIC_APPWRITE_SETTINGS_COLLECTION_ID=$EXPO_PUBLIC_APPWRITE_SETTINGS_COLLECTION_ID \
    EXPO_PUBLIC_APPWRITE_RECORDINGS_COLLECTION_ID=$EXPO_PUBLIC_APPWRITE_RECORDINGS_COLLECTION_ID \
    EXPO_PUBLIC_APPWRITE_SEGMENTS_COLLECTION_ID=$EXPO_PUBLIC_APPWRITE_SEGMENTS_COLLECTION_ID \
    EXPO_PUBLIC_APPWRITE_BUCKET_ID=$EXPO_PUBLIC_APPWRITE_BUCKET_ID \
    CI=1

COPY package.json package-lock.json ./
RUN npm ci

COPY . .
RUN npx expo export -p web

FROM nginx:1.27-alpine AS runner
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80
